#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Carrito_Compras")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Usuario(Tbl_Usuario instance);
    partial void UpdateTbl_Usuario(Tbl_Usuario instance);
    partial void DeleteTbl_Usuario(Tbl_Usuario instance);
    partial void InsertTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void UpdateTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void DeleteTbl_TipoUsuario(Tbl_TipoUsuario instance);
    partial void InsertTbl_Proveedor(Tbl_Proveedor instance);
    partial void UpdateTbl_Proveedor(Tbl_Proveedor instance);
    partial void DeleteTbl_Proveedor(Tbl_Proveedor instance);
    partial void InsertTbl_Producto(Tbl_Producto instance);
    partial void UpdateTbl_Producto(Tbl_Producto instance);
    partial void DeleteTbl_Producto(Tbl_Producto instance);
    partial void InsertTbl_Pedido(Tbl_Pedido instance);
    partial void UpdateTbl_Pedido(Tbl_Pedido instance);
    partial void DeleteTbl_Pedido(Tbl_Pedido instance);
    partial void InsertTbl_DetallePedido(Tbl_DetallePedido instance);
    partial void UpdateTbl_DetallePedido(Tbl_DetallePedido instance);
    partial void DeleteTbl_DetallePedido(Tbl_DetallePedido instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.Carrito_ComprasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this.GetTable<Tbl_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_TipoUsuario> Tbl_TipoUsuario
		{
			get
			{
				return this.GetTable<Tbl_TipoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Proveedor> Tbl_Proveedor
		{
			get
			{
				return this.GetTable<Tbl_Proveedor>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Producto> Tbl_Producto
		{
			get
			{
				return this.GetTable<Tbl_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Pedido> Tbl_Pedido
		{
			get
			{
				return this.GetTable<Tbl_Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_DetallePedido> Tbl_DetallePedido
		{
			get
			{
				return this.GetTable<Tbl_DetallePedido>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Usuario")]
	public partial class Tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_nombre;
		
		private string _usu_correo;
		
		private string _usu_pass;
		
		private string _usu_direccion;
		
		private string _usu_nick;
		
		private string _usu_telefono;
		
		private System.Nullable<char> _usu_estado;
		
		private System.Nullable<int> _tusu_id;
		
		private EntitySet<Tbl_Pedido> _Tbl_Pedido;
		
		private EntityRef<Tbl_TipoUsuario> _Tbl_TipoUsuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_nombreChanging(string value);
    partial void Onusu_nombreChanged();
    partial void Onusu_correoChanging(string value);
    partial void Onusu_correoChanged();
    partial void Onusu_passChanging(string value);
    partial void Onusu_passChanged();
    partial void Onusu_direccionChanging(string value);
    partial void Onusu_direccionChanged();
    partial void Onusu_nickChanging(string value);
    partial void Onusu_nickChanged();
    partial void Onusu_telefonoChanging(string value);
    partial void Onusu_telefonoChanged();
    partial void Onusu_estadoChanging(System.Nullable<char> value);
    partial void Onusu_estadoChanged();
    partial void Ontusu_idChanging(System.Nullable<int> value);
    partial void Ontusu_idChanged();
    #endregion
		
		public Tbl_Usuario()
		{
			this._Tbl_Pedido = new EntitySet<Tbl_Pedido>(new Action<Tbl_Pedido>(this.attach_Tbl_Pedido), new Action<Tbl_Pedido>(this.detach_Tbl_Pedido));
			this._Tbl_TipoUsuario = default(EntityRef<Tbl_TipoUsuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombre", DbType="VarChar(100)")]
		public string usu_nombre
		{
			get
			{
				return this._usu_nombre;
			}
			set
			{
				if ((this._usu_nombre != value))
				{
					this.Onusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._usu_nombre = value;
					this.SendPropertyChanged("usu_nombre");
					this.Onusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_correo", DbType="VarChar(100)")]
		public string usu_correo
		{
			get
			{
				return this._usu_correo;
			}
			set
			{
				if ((this._usu_correo != value))
				{
					this.Onusu_correoChanging(value);
					this.SendPropertyChanging();
					this._usu_correo = value;
					this.SendPropertyChanged("usu_correo");
					this.Onusu_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_pass", DbType="VarChar(100)")]
		public string usu_pass
		{
			get
			{
				return this._usu_pass;
			}
			set
			{
				if ((this._usu_pass != value))
				{
					this.Onusu_passChanging(value);
					this.SendPropertyChanging();
					this._usu_pass = value;
					this.SendPropertyChanged("usu_pass");
					this.Onusu_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_direccion", DbType="VarChar(100)")]
		public string usu_direccion
		{
			get
			{
				return this._usu_direccion;
			}
			set
			{
				if ((this._usu_direccion != value))
				{
					this.Onusu_direccionChanging(value);
					this.SendPropertyChanging();
					this._usu_direccion = value;
					this.SendPropertyChanged("usu_direccion");
					this.Onusu_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nick", DbType="VarChar(100)")]
		public string usu_nick
		{
			get
			{
				return this._usu_nick;
			}
			set
			{
				if ((this._usu_nick != value))
				{
					this.Onusu_nickChanging(value);
					this.SendPropertyChanging();
					this._usu_nick = value;
					this.SendPropertyChanged("usu_nick");
					this.Onusu_nickChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_telefono", DbType="VarChar(100)")]
		public string usu_telefono
		{
			get
			{
				return this._usu_telefono;
			}
			set
			{
				if ((this._usu_telefono != value))
				{
					this.Onusu_telefonoChanging(value);
					this.SendPropertyChanging();
					this._usu_telefono = value;
					this.SendPropertyChanged("usu_telefono");
					this.Onusu_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="Char(1)")]
		public System.Nullable<char> usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", DbType="Int")]
		public System.Nullable<int> tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					if (this._Tbl_TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Usuario_Tbl_Pedido", Storage="_Tbl_Pedido", ThisKey="usu_id", OtherKey="usu_id")]
		public EntitySet<Tbl_Pedido> Tbl_Pedido
		{
			get
			{
				return this._Tbl_Pedido;
			}
			set
			{
				this._Tbl_Pedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TipoUsuario_Tbl_Usuario", Storage="_Tbl_TipoUsuario", ThisKey="tusu_id", OtherKey="tusu_id", IsForeignKey=true)]
		public Tbl_TipoUsuario Tbl_TipoUsuario
		{
			get
			{
				return this._Tbl_TipoUsuario.Entity;
			}
			set
			{
				Tbl_TipoUsuario previousValue = this._Tbl_TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_TipoUsuario.Entity = null;
						previousValue.Tbl_Usuario.Remove(this);
					}
					this._Tbl_TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Tbl_Usuario.Add(this);
						this._tusu_id = value.tusu_id;
					}
					else
					{
						this._tusu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_TipoUsuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Pedido(Tbl_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Usuario = this;
		}
		
		private void detach_Tbl_Pedido(Tbl_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_TipoUsuario")]
	public partial class Tbl_TipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tusu_id;
		
		private string _tusu_nombre;
		
		private System.Nullable<char> _tusu_estado;
		
		private EntitySet<Tbl_Usuario> _Tbl_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontusu_idChanging(int value);
    partial void Ontusu_idChanged();
    partial void Ontusu_nombreChanging(string value);
    partial void Ontusu_nombreChanged();
    partial void Ontusu_estadoChanging(System.Nullable<char> value);
    partial void Ontusu_estadoChanged();
    #endregion
		
		public Tbl_TipoUsuario()
		{
			this._Tbl_Usuario = new EntitySet<Tbl_Usuario>(new Action<Tbl_Usuario>(this.attach_Tbl_Usuario), new Action<Tbl_Usuario>(this.detach_Tbl_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tusu_id
		{
			get
			{
				return this._tusu_id;
			}
			set
			{
				if ((this._tusu_id != value))
				{
					this.Ontusu_idChanging(value);
					this.SendPropertyChanging();
					this._tusu_id = value;
					this.SendPropertyChanged("tusu_id");
					this.Ontusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_nombre", DbType="VarChar(50)")]
		public string tusu_nombre
		{
			get
			{
				return this._tusu_nombre;
			}
			set
			{
				if ((this._tusu_nombre != value))
				{
					this.Ontusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._tusu_nombre = value;
					this.SendPropertyChanged("tusu_nombre");
					this.Ontusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tusu_estado", DbType="Char(1)")]
		public System.Nullable<char> tusu_estado
		{
			get
			{
				return this._tusu_estado;
			}
			set
			{
				if ((this._tusu_estado != value))
				{
					this.Ontusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._tusu_estado = value;
					this.SendPropertyChanged("tusu_estado");
					this.Ontusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_TipoUsuario_Tbl_Usuario", Storage="_Tbl_Usuario", ThisKey="tusu_id", OtherKey="tusu_id")]
		public EntitySet<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this._Tbl_Usuario;
			}
			set
			{
				this._Tbl_Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TipoUsuario = this;
		}
		
		private void detach_Tbl_Usuario(Tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_TipoUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Proveedor")]
	public partial class Tbl_Proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _prov_id;
		
		private string _prov_nombre;
		
		private System.Nullable<char> _prov_estado;
		
		private EntitySet<Tbl_Pedido> _Tbl_Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprov_idChanging(int value);
    partial void Onprov_idChanged();
    partial void Onprov_nombreChanging(string value);
    partial void Onprov_nombreChanged();
    partial void Onprov_estadoChanging(System.Nullable<char> value);
    partial void Onprov_estadoChanged();
    #endregion
		
		public Tbl_Proveedor()
		{
			this._Tbl_Pedido = new EntitySet<Tbl_Pedido>(new Action<Tbl_Pedido>(this.attach_Tbl_Pedido), new Action<Tbl_Pedido>(this.detach_Tbl_Pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int prov_id
		{
			get
			{
				return this._prov_id;
			}
			set
			{
				if ((this._prov_id != value))
				{
					this.Onprov_idChanging(value);
					this.SendPropertyChanging();
					this._prov_id = value;
					this.SendPropertyChanged("prov_id");
					this.Onprov_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_nombre", DbType="VarChar(100)")]
		public string prov_nombre
		{
			get
			{
				return this._prov_nombre;
			}
			set
			{
				if ((this._prov_nombre != value))
				{
					this.Onprov_nombreChanging(value);
					this.SendPropertyChanging();
					this._prov_nombre = value;
					this.SendPropertyChanged("prov_nombre");
					this.Onprov_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prov_estado", DbType="Char(1)")]
		public System.Nullable<char> prov_estado
		{
			get
			{
				return this._prov_estado;
			}
			set
			{
				if ((this._prov_estado != value))
				{
					this.Onprov_estadoChanging(value);
					this.SendPropertyChanging();
					this._prov_estado = value;
					this.SendPropertyChanged("prov_estado");
					this.Onprov_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Proveedor_Tbl_Pedido", Storage="_Tbl_Pedido", ThisKey="prov_id", OtherKey="usu_id")]
		public EntitySet<Tbl_Pedido> Tbl_Pedido
		{
			get
			{
				return this._Tbl_Pedido;
			}
			set
			{
				this._Tbl_Pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Pedido(Tbl_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Proveedor = this;
		}
		
		private void detach_Tbl_Pedido(Tbl_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Producto")]
	public partial class Tbl_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<char> _pro_estado;
		
		private string _pro_descripcion;
		
		private System.Nullable<int> _pro_precio;
		
		private string _pro_foto;
		
		private string _pro_tipo;
		
		private EntitySet<Tbl_Pedido> _Tbl_Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_estadoChanging(System.Nullable<char> value);
    partial void Onpro_estadoChanged();
    partial void Onpro_descripcionChanging(string value);
    partial void Onpro_descripcionChanged();
    partial void Onpro_precioChanging(System.Nullable<int> value);
    partial void Onpro_precioChanged();
    partial void Onpro_fotoChanging(string value);
    partial void Onpro_fotoChanged();
    partial void Onpro_tipoChanging(string value);
    partial void Onpro_tipoChanged();
    #endregion
		
		public Tbl_Producto()
		{
			this._Tbl_Pedido = new EntitySet<Tbl_Pedido>(new Action<Tbl_Pedido>(this.attach_Tbl_Pedido), new Action<Tbl_Pedido>(this.detach_Tbl_Pedido));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="VarChar(100)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Char(1)")]
		public System.Nullable<char> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_descripcion", DbType="VarChar(100)")]
		public string pro_descripcion
		{
			get
			{
				return this._pro_descripcion;
			}
			set
			{
				if ((this._pro_descripcion != value))
				{
					this.Onpro_descripcionChanging(value);
					this.SendPropertyChanging();
					this._pro_descripcion = value;
					this.SendPropertyChanged("pro_descripcion");
					this.Onpro_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio", DbType="Int")]
		public System.Nullable<int> pro_precio
		{
			get
			{
				return this._pro_precio;
			}
			set
			{
				if ((this._pro_precio != value))
				{
					this.Onpro_precioChanging(value);
					this.SendPropertyChanging();
					this._pro_precio = value;
					this.SendPropertyChanged("pro_precio");
					this.Onpro_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_foto", DbType="VarChar(100)")]
		public string pro_foto
		{
			get
			{
				return this._pro_foto;
			}
			set
			{
				if ((this._pro_foto != value))
				{
					this.Onpro_fotoChanging(value);
					this.SendPropertyChanging();
					this._pro_foto = value;
					this.SendPropertyChanged("pro_foto");
					this.Onpro_fotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_tipo", DbType="VarChar(100)")]
		public string pro_tipo
		{
			get
			{
				return this._pro_tipo;
			}
			set
			{
				if ((this._pro_tipo != value))
				{
					this.Onpro_tipoChanging(value);
					this.SendPropertyChanging();
					this._pro_tipo = value;
					this.SendPropertyChanged("pro_tipo");
					this.Onpro_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Producto_Tbl_Pedido", Storage="_Tbl_Pedido", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<Tbl_Pedido> Tbl_Pedido
		{
			get
			{
				return this._Tbl_Pedido;
			}
			set
			{
				this._Tbl_Pedido.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Pedido(Tbl_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Producto = this;
		}
		
		private void detach_Tbl_Pedido(Tbl_Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Pedido")]
	public partial class Tbl_Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ped_id;
		
		private System.Nullable<System.DateTime> _ped_fecha;
		
		private string _ped_estado;
		
		private System.Nullable<decimal> _ped_total;
		
		private System.Nullable<int> _pro_id;
		
		private System.Nullable<int> _usu_id;
		
		private EntitySet<Tbl_DetallePedido> _Tbl_DetallePedido;
		
		private EntityRef<Tbl_Producto> _Tbl_Producto;
		
		private EntityRef<Tbl_Proveedor> _Tbl_Proveedor;
		
		private EntityRef<Tbl_Usuario> _Tbl_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onped_idChanging(int value);
    partial void Onped_idChanged();
    partial void Onped_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onped_fechaChanged();
    partial void Onped_estadoChanging(string value);
    partial void Onped_estadoChanged();
    partial void Onped_totalChanging(System.Nullable<decimal> value);
    partial void Onped_totalChanged();
    partial void Onpro_idChanging(System.Nullable<int> value);
    partial void Onpro_idChanged();
    partial void Onusu_idChanging(System.Nullable<int> value);
    partial void Onusu_idChanged();
    #endregion
		
		public Tbl_Pedido()
		{
			this._Tbl_DetallePedido = new EntitySet<Tbl_DetallePedido>(new Action<Tbl_DetallePedido>(this.attach_Tbl_DetallePedido), new Action<Tbl_DetallePedido>(this.detach_Tbl_DetallePedido));
			this._Tbl_Producto = default(EntityRef<Tbl_Producto>);
			this._Tbl_Proveedor = default(EntityRef<Tbl_Proveedor>);
			this._Tbl_Usuario = default(EntityRef<Tbl_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ped_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ped_id
		{
			get
			{
				return this._ped_id;
			}
			set
			{
				if ((this._ped_id != value))
				{
					this.Onped_idChanging(value);
					this.SendPropertyChanging();
					this._ped_id = value;
					this.SendPropertyChanged("ped_id");
					this.Onped_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ped_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> ped_fecha
		{
			get
			{
				return this._ped_fecha;
			}
			set
			{
				if ((this._ped_fecha != value))
				{
					this.Onped_fechaChanging(value);
					this.SendPropertyChanging();
					this._ped_fecha = value;
					this.SendPropertyChanged("ped_fecha");
					this.Onped_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ped_estado", DbType="VarChar(50)")]
		public string ped_estado
		{
			get
			{
				return this._ped_estado;
			}
			set
			{
				if ((this._ped_estado != value))
				{
					this.Onped_estadoChanging(value);
					this.SendPropertyChanging();
					this._ped_estado = value;
					this.SendPropertyChanged("ped_estado");
					this.Onped_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ped_total", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ped_total
		{
			get
			{
				return this._ped_total;
			}
			set
			{
				if ((this._ped_total != value))
				{
					this.Onped_totalChanging(value);
					this.SendPropertyChanging();
					this._ped_total = value;
					this.SendPropertyChanged("ped_total");
					this.Onped_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int")]
		public System.Nullable<int> pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._Tbl_Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", DbType="Int")]
		public System.Nullable<int> usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					if ((this._Tbl_Proveedor.HasLoadedOrAssignedValue || this._Tbl_Usuario.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Pedido_Tbl_DetallePedido", Storage="_Tbl_DetallePedido", ThisKey="ped_id", OtherKey="ped_id")]
		public EntitySet<Tbl_DetallePedido> Tbl_DetallePedido
		{
			get
			{
				return this._Tbl_DetallePedido;
			}
			set
			{
				this._Tbl_DetallePedido.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Producto_Tbl_Pedido", Storage="_Tbl_Producto", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true)]
		public Tbl_Producto Tbl_Producto
		{
			get
			{
				return this._Tbl_Producto.Entity;
			}
			set
			{
				Tbl_Producto previousValue = this._Tbl_Producto.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Producto.Entity = null;
						previousValue.Tbl_Pedido.Remove(this);
					}
					this._Tbl_Producto.Entity = value;
					if ((value != null))
					{
						value.Tbl_Pedido.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Proveedor_Tbl_Pedido", Storage="_Tbl_Proveedor", ThisKey="usu_id", OtherKey="prov_id", IsForeignKey=true)]
		public Tbl_Proveedor Tbl_Proveedor
		{
			get
			{
				return this._Tbl_Proveedor.Entity;
			}
			set
			{
				Tbl_Proveedor previousValue = this._Tbl_Proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Proveedor.Entity = null;
						previousValue.Tbl_Pedido.Remove(this);
					}
					this._Tbl_Proveedor.Entity = value;
					if ((value != null))
					{
						value.Tbl_Pedido.Add(this);
						this._usu_id = value.prov_id;
					}
					else
					{
						this._usu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Proveedor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Usuario_Tbl_Pedido", Storage="_Tbl_Usuario", ThisKey="usu_id", OtherKey="usu_id", IsForeignKey=true)]
		public Tbl_Usuario Tbl_Usuario
		{
			get
			{
				return this._Tbl_Usuario.Entity;
			}
			set
			{
				Tbl_Usuario previousValue = this._Tbl_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Usuario.Entity = null;
						previousValue.Tbl_Pedido.Remove(this);
					}
					this._Tbl_Usuario.Entity = value;
					if ((value != null))
					{
						value.Tbl_Pedido.Add(this);
						this._usu_id = value.usu_id;
					}
					else
					{
						this._usu_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_DetallePedido(Tbl_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Pedido = this;
		}
		
		private void detach_Tbl_DetallePedido(Tbl_DetallePedido entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_DetallePedido")]
	public partial class Tbl_DetallePedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _det_id;
		
		private System.Nullable<decimal> _det_preciounitario;
		
		private System.Nullable<int> _det_cantidad;
		
		private System.Nullable<int> _ped_id;
		
		private EntityRef<Tbl_Pedido> _Tbl_Pedido;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondet_idChanging(int value);
    partial void Ondet_idChanged();
    partial void Ondet_preciounitarioChanging(System.Nullable<decimal> value);
    partial void Ondet_preciounitarioChanged();
    partial void Ondet_cantidadChanging(System.Nullable<int> value);
    partial void Ondet_cantidadChanged();
    partial void Onped_idChanging(System.Nullable<int> value);
    partial void Onped_idChanged();
    #endregion
		
		public Tbl_DetallePedido()
		{
			this._Tbl_Pedido = default(EntityRef<Tbl_Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_det_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int det_id
		{
			get
			{
				return this._det_id;
			}
			set
			{
				if ((this._det_id != value))
				{
					this.Ondet_idChanging(value);
					this.SendPropertyChanging();
					this._det_id = value;
					this.SendPropertyChanged("det_id");
					this.Ondet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_det_preciounitario", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> det_preciounitario
		{
			get
			{
				return this._det_preciounitario;
			}
			set
			{
				if ((this._det_preciounitario != value))
				{
					this.Ondet_preciounitarioChanging(value);
					this.SendPropertyChanging();
					this._det_preciounitario = value;
					this.SendPropertyChanged("det_preciounitario");
					this.Ondet_preciounitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_det_cantidad", DbType="Int")]
		public System.Nullable<int> det_cantidad
		{
			get
			{
				return this._det_cantidad;
			}
			set
			{
				if ((this._det_cantidad != value))
				{
					this.Ondet_cantidadChanging(value);
					this.SendPropertyChanging();
					this._det_cantidad = value;
					this.SendPropertyChanged("det_cantidad");
					this.Ondet_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ped_id", DbType="Int")]
		public System.Nullable<int> ped_id
		{
			get
			{
				return this._ped_id;
			}
			set
			{
				if ((this._ped_id != value))
				{
					if (this._Tbl_Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onped_idChanging(value);
					this.SendPropertyChanging();
					this._ped_id = value;
					this.SendPropertyChanged("ped_id");
					this.Onped_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Pedido_Tbl_DetallePedido", Storage="_Tbl_Pedido", ThisKey="ped_id", OtherKey="ped_id", IsForeignKey=true)]
		public Tbl_Pedido Tbl_Pedido
		{
			get
			{
				return this._Tbl_Pedido.Entity;
			}
			set
			{
				Tbl_Pedido previousValue = this._Tbl_Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Pedido.Entity = null;
						previousValue.Tbl_DetallePedido.Remove(this);
					}
					this._Tbl_Pedido.Entity = value;
					if ((value != null))
					{
						value.Tbl_DetallePedido.Add(this);
						this._ped_id = value.ped_id;
					}
					else
					{
						this._ped_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
